CREATE TABLE STORAGE
(
    ID                NUMBER PRIMARY KEY,
    FORMATS_SUPPORTED NVARCHAR2(50) NOT NULL,
    COUNTRY           NVARCHAR2(50) NOT NULL,
    STORAGE_SIZE      NUMBER CHECK (STORAGE_SIZE > 0),
    FREE_SPACE        NUMBER,
    CHECK (FREE_SPACE BETWEEN 0 AND STORAGE_SIZE)
);